### ISSUE TITLE
Errors in Firefox

### ISSUE THREAD

**Issue by jochec** [stefanuebe/vaadin-html5-drag-and-drop#4] opened 2019-01-03 09:59 UTC
Hi, I'm getting following errors when using Firefox:

`NoModificationAllowedError: Modifications are not allowed for this document client-CAF80B1F92BD4481C6D5EC01BC2D55AE.cache.js line 971 > Function:3`

`TypeError: e.target.classList is undefined[Learn More] client-CAF80B1F92BD4481C6D5EC01BC2D55AE.cache.js line 971 > Function:3:59`

Tested on Windows 10.
Reproducible on [https://stefan.app.fi/dnd-demo/](https://stefan.app.fi/dnd-demo/) with Firefox 64.0.

**Comment by stefanuebe** [comment] 2019-01-07 12:48
Hi, the 2nd has been fixed, will be part of version 1.0.4. The 1st problem I get, too, but I cannot tell the reason for that. Tried several things and will do further research, but could not find a fast solution for now. Might be a FF bug if it occurs now, but not before.

**Comment by stefanuebe** [comment] 2019-01-07 12:54
Sidenote: when running in production mode, the error appears in the dev console of firefox only, but not as a Vaadin error message. The dnd should work nevertheless.

**Comment by us31t** [comment] 2019-01-24 19:15
Hi Stefan, 
got the same issue here. I found this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1267942

Could the bug be here? 
https://github.com/stefanuebe/vaadin-html5-drag-and-drop/blob/ffc0ebd39a2a496e424edabddbe7fc6b869ae9f0/addon/src/main/java/org/vaadin/stefan/dnd/drag/DragSourceExtension.java#L85

TY! Kind regards
Robert

**Comment by stefanuebe** [comment] 2019-02-01 09:00
Thanks, the mozilla bug description helped.

Looks like it was the `dragend` event listener, that set the transfer data to `null`. According to Mozillas documentation, a writing operation is only allowed in `dragstart`. 

Removed the line. The error should not appear any more in 1.0.5.

**Comment by us31t** [comment] 2019-02-01 13:21
Hello Stefan 

You are great! Thank you very much for the fast fix! You saved my month. 

Kind regards
Robert

**Comment by us31t** [comment] 2019-02-01 14:04
Sorry now I get a different error. 

(TypeError) : $0 is null client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197:18
vB
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197:18
cn
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:955:293
bn
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:732:80
dn
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:585:58
jt
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972:357
it
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:928:276
gt
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:564:57
Pq
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:479:18
mr
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:19000
aA
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:863:192
Rq
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:975:582
gr
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:18673
zj
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:743:101
Gj
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:7054
fm
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:830:164
Mm
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:12468
rm/a.onload<
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:931:98
sb
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:420:27
vb
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:847:56
ub/<
http://localhost:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:604:46
The error has occurred in the JS code: '$0, $0.addEventListener('dragstart', e => {e.stopPropagation(); if(typeof e.target.classList !== 'undefined') {	e.target.classList.add('dragged','div-dragged');	e.dataTransfer.clearData();	e.dataTransfer.effectAllowed = 'move';	e.dataTransfer.setData('text/plain', e.target.id);	}})' client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:183:18
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972:237
(TypeError) : $0 is null client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197:18

**Comment by stefanuebe** [comment] 2019-02-05 14:59
Does it occur in the demo (I don't get an error here)?  If not, can you give me the source code as an example?

**Comment by us31t** [comment] 2019-02-05 15:24
I am currently extremely busy, it will take a view days/weeks. When I will come again to refactor the D&D part I will try to produce a exact or standalone example. 

Thanks for your help!

**Comment by us31t** [comment] 2019-02-07 09:47
Ok, I can not reproduce it anymore. Close

**Comment by us31t** [comment] 2019-02-07 10:17
When the div is "full" it has problems during updating the browser. This has nothing to do with your plugin, but HTML D&D.

I added now this functionality to my code. Maybe it makes sense to add it in the plugin? (Sorry I know this is the wrong place)

> Correctly handling dragEnter, dragLeave and dragOver
> 
> There’s one common pitfall of all of these events — they fire like crazy if you have child elements in the target element in which the drop occurs. The easiest thing we’ve figured out:
> 
>     Whenever dragEnter on your target element fires, give it a css class like ‘.drag’
>     Whenever dragLeave on your target element fires, remove the css class
>     Add the css class to your document that looks like this:
> 
> .drag * {
>  pointer-events: none;
> }
https://medium.com/@reiberdatschi/common-pitfalls-with-html5-drag-n-drop-api-9f011a09ee6c

**Closed** 2019-02-11 15:17 UTC
Labels: bug
